<?php

namespace Tests;

use App\Models\Manager;
use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    public Manager $manager;
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('config:clear');
        $this->manager = $this->createManager();
    }
    /**
     * @return Manager
     */
    private function createManager() : Manager
    {
        return Manager::create([
            'email'    => 'admintest123@gmail.com',
            'mobile'    => 512222222,
            'username' => "admin_test",
            'password' => bcrypt(123456789)
        ]);
    }

    /**
     * @return string[]
     */
    protected function createToken() : array
    {
        $this->user = $user = User::create([
             'full_name'   => "mahmoud_test",
             'email'       => 'mahmoud_test@gmail.com',
             'mobile'      => 512345678,
             'is_verified' => 1,
             'otp_code'    => 12345,
             'password'    => bcrypt(123456789)
        ]);
        return [
            'Authorization' => 'Bearer '.$user->createToken('MyApp', ['customer'])->accessToken,
            'Accept'        => 'application/json',
            'Content-Type'  =>  'application/json'
            ];
    }
}
